import InfoBox from "./InfoBox";
import SearchBox from "./SearchBox";
import { useState } from "react";


export default function WeatherInfo (){

    let [weatherInfo,setWeatherInfo]=useState([
        {
          city:"Delhi",
          min:"No Rain for at least 120 Minutes",
        },
        {
          time:20,
          temp:2,
          real:4,
          rain:0,
          wind:19,
          deg:310,
          direction:"ENE",
          cloud:40,
          visible:16,
          dew:18,
          humidity:49,
          num:1,
          iconPhrase:"Mostly sunny",
        },
        {
          time:20,
          temp:2,
          real:4,
          rain:0,
          wind:19,
          deg:310,
          direction:"NE",
          cloud:40,
          visible:16,
          dew:18,
          humidity:49,
          num:1,
          iconPhrase:"Mostly sunny",
        },
        {
          time:20,
          temp:2,
          real:4,
          rain:0,
          wind:19,
          deg:310,
          direction:"NE",
          cloud:40,
          visible:16,
          dew:18,
          humidity:49,
          num:1,
          iconPhrase:"Mostly sunny",
        },
        {
          time:20,
          temp:2,
          real:4,
          rain:0,
          wind:19,
          deg:310,
          direction:"NE",
          cloud:40,
          visible:16,
          dew:18,
          humidity:49,
          num:1,
          iconPhrase:"Mostly sunny",
        },
        {
          time:20,
          temp:2,
          real:4,
          rain:0,
          wind:19,
          deg:310,
          direction:"NE",
          cloud:40,
          visible:16,
          dew:18,
          humidity:49,
          num:1,
          iconPhrase:"Mostly sunny",
        },
        {
          time:20,
          temp:2,
          real:4,
          rain:0,
          wind:19,
          deg:310,
          direction:"NE",
          cloud:40,
          visible:16,
          dew:18,
          humidity:49,
          num:1,
          iconPhrase:"Mostly sunny",
        },
        {
          time:20,
          temp:2,
          real:4,
          rain:0,
          wind:19,
          deg:310,
          direction:"NE",
          cloud:40,
          visible:16,
          dew:18,
          humidity:49,
          num:1,
          iconPhrase:"Mostly sunny",
        },
        {
          time:20,
          temp:2,
          real:4,
          rain:0,
          wind:19,
          deg:310,
          direction:"NE",
          cloud:40,
          visible:16,
          dew:18,
          humidity:49,
          num:1,
          iconPhrase:"Mostly sunny",
        },
        {
          time:20,
          temp:2,
          real:4,
          rain:0,
          wind:19,
          deg:310,
          direction:"NE",
          cloud:40,
          visible:16,
          dew:18,
          humidity:1,
          num:1,
          iconPhrase:"Mostly sunny",
        },
        {
          sunrise:7,
          sunriseM:15,
          sunset:16,
          sunsetM:15,
          moonrise:15,
          moonriseM:25,
          moonset:6,
          moonsetM:25,
          minTemp:8,
          maxTemp:16,
          realMin:10,
          realMax:20,
          air:"Unhealthy",
          num:14,
          phrase:"Sunny",
          speed:16,
          deg:310,
          direction:"NN",
          currTemp:20,
        },
      ]);



    let updateInfo=(newInfo)=>{
        setWeatherInfo(newInfo);
    };

    return(
        <div style={{textAlign:"center"}}>
            <SearchBox updateInfo={updateInfo}/>
            <InfoBox info={weatherInfo}/>
        </div>
    )
}